// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/some-awesome-hub.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MethodOneRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOneRequest) Reset()         { *m = MethodOneRequest{} }
func (m *MethodOneRequest) String() string { return proto.CompactTextString(m) }
func (*MethodOneRequest) ProtoMessage()    {}
func (*MethodOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{0}
}

func (m *MethodOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOneRequest.Unmarshal(m, b)
}
func (m *MethodOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOneRequest.Marshal(b, m, deterministic)
}
func (m *MethodOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOneRequest.Merge(m, src)
}
func (m *MethodOneRequest) XXX_Size() int {
	return xxx_messageInfo_MethodOneRequest.Size(m)
}
func (m *MethodOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOneRequest proto.InternalMessageInfo

type MethodOneResponse struct {
	FieldOne             string   `protobuf:"bytes,1,opt,name=fieldOne,proto3" json:"fieldOne,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodOneResponse) Reset()         { *m = MethodOneResponse{} }
func (m *MethodOneResponse) String() string { return proto.CompactTextString(m) }
func (*MethodOneResponse) ProtoMessage()    {}
func (*MethodOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{1}
}

func (m *MethodOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOneResponse.Unmarshal(m, b)
}
func (m *MethodOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOneResponse.Marshal(b, m, deterministic)
}
func (m *MethodOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOneResponse.Merge(m, src)
}
func (m *MethodOneResponse) XXX_Size() int {
	return xxx_messageInfo_MethodOneResponse.Size(m)
}
func (m *MethodOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOneResponse proto.InternalMessageInfo

func (m *MethodOneResponse) GetFieldOne() string {
	if m != nil {
		return m.FieldOne
	}
	return ""
}

func (m *MethodOneResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type MethodTwoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodTwoRequest) Reset()         { *m = MethodTwoRequest{} }
func (m *MethodTwoRequest) String() string { return proto.CompactTextString(m) }
func (*MethodTwoRequest) ProtoMessage()    {}
func (*MethodTwoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{2}
}

func (m *MethodTwoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodTwoRequest.Unmarshal(m, b)
}
func (m *MethodTwoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodTwoRequest.Marshal(b, m, deterministic)
}
func (m *MethodTwoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodTwoRequest.Merge(m, src)
}
func (m *MethodTwoRequest) XXX_Size() int {
	return xxx_messageInfo_MethodTwoRequest.Size(m)
}
func (m *MethodTwoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodTwoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MethodTwoRequest proto.InternalMessageInfo

type MethodTwoResponse struct {
	FieldOne             string   `protobuf:"bytes,1,opt,name=fieldOne,proto3" json:"fieldOne,omitempty"`
	FieldsTwo            []string `protobuf:"bytes,2,rep,name=fieldsTwo,proto3" json:"fieldsTwo,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodTwoResponse) Reset()         { *m = MethodTwoResponse{} }
func (m *MethodTwoResponse) String() string { return proto.CompactTextString(m) }
func (*MethodTwoResponse) ProtoMessage()    {}
func (*MethodTwoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{3}
}

func (m *MethodTwoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodTwoResponse.Unmarshal(m, b)
}
func (m *MethodTwoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodTwoResponse.Marshal(b, m, deterministic)
}
func (m *MethodTwoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodTwoResponse.Merge(m, src)
}
func (m *MethodTwoResponse) XXX_Size() int {
	return xxx_messageInfo_MethodTwoResponse.Size(m)
}
func (m *MethodTwoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodTwoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MethodTwoResponse proto.InternalMessageInfo

func (m *MethodTwoResponse) GetFieldOne() string {
	if m != nil {
		return m.FieldOne
	}
	return ""
}

func (m *MethodTwoResponse) GetFieldsTwo() []string {
	if m != nil {
		return m.FieldsTwo
	}
	return nil
}

func (m *MethodTwoResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type MethodThreeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodThreeRequest) Reset()         { *m = MethodThreeRequest{} }
func (m *MethodThreeRequest) String() string { return proto.CompactTextString(m) }
func (*MethodThreeRequest) ProtoMessage()    {}
func (*MethodThreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{4}
}

func (m *MethodThreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodThreeRequest.Unmarshal(m, b)
}
func (m *MethodThreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodThreeRequest.Marshal(b, m, deterministic)
}
func (m *MethodThreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodThreeRequest.Merge(m, src)
}
func (m *MethodThreeRequest) XXX_Size() int {
	return xxx_messageInfo_MethodThreeRequest.Size(m)
}
func (m *MethodThreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodThreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MethodThreeRequest proto.InternalMessageInfo

type MethodThreeResponse struct {
	FieldTwo             string   `protobuf:"bytes,1,opt,name=fieldTwo,proto3" json:"fieldTwo,omitempty"`
	FieldThree           uint64   `protobuf:"varint,2,opt,name=fieldThree,proto3" json:"fieldThree,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodThreeResponse) Reset()         { *m = MethodThreeResponse{} }
func (m *MethodThreeResponse) String() string { return proto.CompactTextString(m) }
func (*MethodThreeResponse) ProtoMessage()    {}
func (*MethodThreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{5}
}

func (m *MethodThreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodThreeResponse.Unmarshal(m, b)
}
func (m *MethodThreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodThreeResponse.Marshal(b, m, deterministic)
}
func (m *MethodThreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodThreeResponse.Merge(m, src)
}
func (m *MethodThreeResponse) XXX_Size() int {
	return xxx_messageInfo_MethodThreeResponse.Size(m)
}
func (m *MethodThreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodThreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MethodThreeResponse proto.InternalMessageInfo

func (m *MethodThreeResponse) GetFieldTwo() string {
	if m != nil {
		return m.FieldTwo
	}
	return ""
}

func (m *MethodThreeResponse) GetFieldThree() uint64 {
	if m != nil {
		return m.FieldThree
	}
	return 0
}

func (m *MethodThreeResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type SayHelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloRequest) Reset()         { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()    {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{6}
}

func (m *SayHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRequest.Unmarshal(m, b)
}
func (m *SayHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRequest.Marshal(b, m, deterministic)
}
func (m *SayHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRequest.Merge(m, src)
}
func (m *SayHelloRequest) XXX_Size() int {
	return xxx_messageInfo_SayHelloRequest.Size(m)
}
func (m *SayHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRequest proto.InternalMessageInfo

type SayHelloResponse struct {
	FieldHello           string   `protobuf:"bytes,1,opt,name=fieldHello,proto3" json:"fieldHello,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloResponse) Reset()         { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()    {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_900c0150587ff780, []int{7}
}

func (m *SayHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloResponse.Unmarshal(m, b)
}
func (m *SayHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloResponse.Marshal(b, m, deterministic)
}
func (m *SayHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloResponse.Merge(m, src)
}
func (m *SayHelloResponse) XXX_Size() int {
	return xxx_messageInfo_SayHelloResponse.Size(m)
}
func (m *SayHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloResponse proto.InternalMessageInfo

func (m *SayHelloResponse) GetFieldHello() string {
	if m != nil {
		return m.FieldHello
	}
	return ""
}

func (m *SayHelloResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*MethodOneRequest)(nil), "pb.MethodOneRequest")
	proto.RegisterType((*MethodOneResponse)(nil), "pb.MethodOneResponse")
	proto.RegisterType((*MethodTwoRequest)(nil), "pb.MethodTwoRequest")
	proto.RegisterType((*MethodTwoResponse)(nil), "pb.MethodTwoResponse")
	proto.RegisterType((*MethodThreeRequest)(nil), "pb.MethodThreeRequest")
	proto.RegisterType((*MethodThreeResponse)(nil), "pb.MethodThreeResponse")
	proto.RegisterType((*SayHelloRequest)(nil), "pb.SayHelloRequest")
	proto.RegisterType((*SayHelloResponse)(nil), "pb.SayHelloResponse")
}

func init() { proto.RegisterFile("test/some-awesome-hub.proto", fileDescriptor_900c0150587ff780) }

var fileDescriptor_900c0150587ff780 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0x49, 0xf2, 0xf1, 0xd1, 0x8c, 0xa0, 0xe9, 0x36, 0x6a, 0x8c, 0x22, 0xa5, 0xa7, 0x5e,
	0x4c, 0x41, 0x11, 0x3c, 0x09, 0x05, 0x0f, 0xbd, 0x88, 0x90, 0xf6, 0x2e, 0x89, 0x8e, 0xa4, 0x90,
	0x74, 0x63, 0x76, 0x43, 0xf0, 0x6f, 0xf7, 0x22, 0xbb, 0x49, 0x76, 0xb7, 0xa9, 0x07, 0x4f, 0x99,
	0xfc, 0x32, 0xef, 0x3d, 0x66, 0x26, 0x70, 0xc9, 0x91, 0xf1, 0x05, 0xa3, 0x05, 0xde, 0x24, 0x0d,
	0xca, 0x67, 0x56, 0xa7, 0x51, 0x59, 0x51, 0x4e, 0x89, 0x5d, 0xa6, 0xe1, 0x05, 0xdf, 0x16, 0xc8,
	0x78, 0x52, 0x94, 0x0b, 0x55, 0xb5, 0x9f, 0x67, 0x04, 0xbc, 0x67, 0xe4, 0x19, 0x7d, 0x7f, 0xd9,
	0x61, 0x8c, 0x9f, 0x35, 0x32, 0x3e, 0x5b, 0xc2, 0xd8, 0x60, 0xac, 0xa4, 0x3b, 0x86, 0x24, 0x84,
	0xd1, 0xc7, 0x16, 0x73, 0xc1, 0x02, 0x6b, 0x6a, 0xcd, 0xdd, 0x58, 0xbd, 0x13, 0x0f, 0x1c, 0xac,
	0xaa, 0xc0, 0x96, 0x58, 0x94, 0xda, 0x76, 0xd3, 0xd0, 0xde, 0xf6, 0xb5, 0xb7, 0x95, 0xec, 0x0f,
	0xb6, 0x57, 0xe0, 0xca, 0x9a, 0x6d, 0x1a, 0x1a, 0xd8, 0x53, 0x67, 0xee, 0xc6, 0x1a, 0xf4, 0xa1,
	0x8e, 0x0e, 0xf5, 0x81, 0x74, 0x01, 0x59, 0x85, 0x6a, 0x9a, 0x37, 0x98, 0xec, 0xd1, 0x41, 0xb0,
	0xf0, 0x36, 0x83, 0x85, 0xf5, 0x35, 0x40, 0x5b, 0x0b, 0x85, 0x1c, 0xeb, 0x5f, 0x6c, 0x90, 0x5f,
	0xa2, 0xc7, 0x70, 0xb2, 0x4e, 0xbe, 0x56, 0x98, 0xe7, 0x6a, 0xdc, 0x27, 0xf0, 0x34, 0xea, 0x42,
	0x7b, 0x63, 0x49, 0xbb, 0x58, 0x83, 0x1c, 0x2e, 0xf2, 0xf6, 0xdb, 0x82, 0xe3, 0x35, 0x2d, 0x70,
	0xd9, 0x1e, 0x76, 0x55, 0xa7, 0xe4, 0x01, 0x5c, 0x75, 0x1e, 0xe2, 0x47, 0x65, 0x1a, 0x0d, 0x2f,
	0x18, 0x9e, 0x0e, 0x68, 0x17, 0xaf, 0x94, 0x62, 0x48, 0x43, 0xa9, 0x8f, 0x64, 0x2a, 0xcd, 0x33,
	0x3d, 0xc2, 0x91, 0xb1, 0x44, 0x72, 0x66, 0x74, 0x19, 0xbb, 0x0e, 0xcf, 0x0f, 0x78, 0xa7, 0xbf,
	0x87, 0x51, 0xbf, 0x0c, 0x32, 0x11, 0x4d, 0x83, 0x6d, 0x85, 0xfe, 0x3e, 0x6c, 0x65, 0xe9, 0x7f,
	0xf9, 0x93, 0xde, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0x14, 0x88, 0xba, 0xe2, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SomeAwesomeHubClient is the client API for SomeAwesomeHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SomeAwesomeHubClient interface {
	MethodOne(ctx context.Context, in *MethodOneRequest, opts ...grpc.CallOption) (*MethodOneResponse, error)
	MethodTwo(ctx context.Context, in *MethodTwoRequest, opts ...grpc.CallOption) (*MethodTwoResponse, error)
	MethodThree(ctx context.Context, in *MethodThreeRequest, opts ...grpc.CallOption) (*MethodThreeResponse, error)
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type someAwesomeHubClient struct {
	cc *grpc.ClientConn
}

func NewSomeAwesomeHubClient(cc *grpc.ClientConn) SomeAwesomeHubClient {
	return &someAwesomeHubClient{cc}
}

func (c *someAwesomeHubClient) MethodOne(ctx context.Context, in *MethodOneRequest, opts ...grpc.CallOption) (*MethodOneResponse, error) {
	out := new(MethodOneResponse)
	err := c.cc.Invoke(ctx, "/pb.SomeAwesomeHub/MethodOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someAwesomeHubClient) MethodTwo(ctx context.Context, in *MethodTwoRequest, opts ...grpc.CallOption) (*MethodTwoResponse, error) {
	out := new(MethodTwoResponse)
	err := c.cc.Invoke(ctx, "/pb.SomeAwesomeHub/MethodTwo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someAwesomeHubClient) MethodThree(ctx context.Context, in *MethodThreeRequest, opts ...grpc.CallOption) (*MethodThreeResponse, error) {
	out := new(MethodThreeResponse)
	err := c.cc.Invoke(ctx, "/pb.SomeAwesomeHub/MethodThree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *someAwesomeHubClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/pb.SomeAwesomeHub/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomeAwesomeHubServer is the server API for SomeAwesomeHub service.
type SomeAwesomeHubServer interface {
	MethodOne(context.Context, *MethodOneRequest) (*MethodOneResponse, error)
	MethodTwo(context.Context, *MethodTwoRequest) (*MethodTwoResponse, error)
	MethodThree(context.Context, *MethodThreeRequest) (*MethodThreeResponse, error)
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

// UnimplementedSomeAwesomeHubServer can be embedded to have forward compatible implementations.
type UnimplementedSomeAwesomeHubServer struct {
}

func (*UnimplementedSomeAwesomeHubServer) MethodOne(ctx context.Context, req *MethodOneRequest) (*MethodOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MethodOne not implemented")
}
func (*UnimplementedSomeAwesomeHubServer) MethodTwo(ctx context.Context, req *MethodTwoRequest) (*MethodTwoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MethodTwo not implemented")
}
func (*UnimplementedSomeAwesomeHubServer) MethodThree(ctx context.Context, req *MethodThreeRequest) (*MethodThreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MethodThree not implemented")
}
func (*UnimplementedSomeAwesomeHubServer) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterSomeAwesomeHubServer(s *grpc.Server, srv SomeAwesomeHubServer) {
	s.RegisterService(&_SomeAwesomeHub_serviceDesc, srv)
}

func _SomeAwesomeHub_MethodOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MethodOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeAwesomeHubServer).MethodOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SomeAwesomeHub/MethodOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeAwesomeHubServer).MethodOne(ctx, req.(*MethodOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeAwesomeHub_MethodTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MethodTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeAwesomeHubServer).MethodTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SomeAwesomeHub/MethodTwo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeAwesomeHubServer).MethodTwo(ctx, req.(*MethodTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeAwesomeHub_MethodThree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MethodThreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeAwesomeHubServer).MethodThree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SomeAwesomeHub/MethodThree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeAwesomeHubServer).MethodThree(ctx, req.(*MethodThreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SomeAwesomeHub_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeAwesomeHubServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SomeAwesomeHub/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeAwesomeHubServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SomeAwesomeHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SomeAwesomeHub",
	HandlerType: (*SomeAwesomeHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MethodOne",
			Handler:    _SomeAwesomeHub_MethodOne_Handler,
		},
		{
			MethodName: "MethodTwo",
			Handler:    _SomeAwesomeHub_MethodTwo_Handler,
		},
		{
			MethodName: "MethodThree",
			Handler:    _SomeAwesomeHub_MethodThree_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _SomeAwesomeHub_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/some-awesome-hub.proto",
}
